* org-make-toc-action
#+BEGIN_HTML
<a href="https://github.com/akirak/org-make-toc-action/actions/workflows/build.yml">
<img src="https://github.com/akirak/org-make-toc-action/actions/workflows/build.yml/badge.svg">
</a>
#+END_HTML

This is a GitHub Action which updates TOCs in Emacs Org mode files.
It uses [[https://github.com/alphapapa/org-make-toc][org-make-toc]] by alphapapa which provides a rich API to fine-grained control of output.
This repository also provides a Docker image and a Nix flake which run an executable version of the library.
** Table of contents                                              :noexport:
:PROPERTIES:
:TOC:      :include siblings :depth 2 :ignore this
:END:
:CONTENTS:
- [[#usage][Usage]]
  - [[#github-action][GitHub Action]]
  - [[#docker-image][Docker image]]
  - [[#nix-flake][Nix flake]]
- [[#credits][Credits]]
:END:
** Usage
*** GitHub Action
This repository contains [[https://github.com/akirak/org-make-toc-action/blob/master/.github/workflows/toc.yml][an example]] workflow which updates the TOC of this document and push the change to the branch.

The action accepts a single required input parameter =patterns= which is a comma-separated glob patterns of target files.
*** Docker image
You can also use [[https://github.com/akirak/org-make-toc-action/pkgs/container/org-make-toc][a Docker image]] from this repository.
It is currently hosted on GitHub Container Registry:

#+begin_src sh
docker run -v $PWD:/data -w /data -t ghcr.io/akirak/org-make-toc:latest README.org
#+end_src

It accepts Org files (not glob patterns) as arguments.
*** Nix flake
This repository contains a Nix flake, so you can run the application using =nix run=, e.g.:

#+begin_src sh
nix run github:akirak/org-make-toc-action -- README.org
#+end_src

Since this is a flake, you can also integrate it with your flake project by using [[https://github.com/cachix/pre-commit-hooks.nix/][pre-commit-hooks.nix]], for example.
The package name is =executable=.
** Credits
- Adam Porter, a.k.a. alphapapa, for writing the [[https://github.com/alphapapa/org-make-toc][org-make-toc]] package.
** COMMENT Meta :noexport:
:PROPERTIES:
:TOC:      ignore
:END:
