name: Update TOC

on:
  push:
    paths:
    - '*.org'

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        patterns: README.org
    - name: Commit changes
      run: |
        if ! git diff --exit-code HEAD; then
          git config --local user.email \
            6270544+github-actions[bot]@users.noreply.github.com
          git config --local user.name \
            github-actions[bot]
          git commit -a -m 'docs: Update TOC by github-actions[bot]'
          git push
        fi
